### ISSUE TITLE
qualmetadata takes forever when accessing quality data

### ISSUE THREAD

**Issue by pabloi** [PittSMLlab/labTools#16]
Qualmetadata (Matlab native) casts data as double when accesing it. This takes FOREVER on big matrices. Behavior can be fixed by just commenting the casting line on MAtlab's function, but this temporal fix does not translate to other users and is lost when updating Matlab.

Solution: copy the file with the commented file to OUR repository, and shadow Matlab's function (i.e. our function will be used BEFORE Matlab's own).

Need to check that this does not lead to weird behavior.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/39176803425625/56682139042569)

**Comment by PittSMLlab** [comment]
Update: issue remains in R2017b, workaround implemented.
