### ISSUE TITLE
merge adaptationData.plotGroupedSubjectsBars and v2

### ISSUE THREAD

**Issue by pabloi** [PittSMLlab/labTools#42]
These two functions do basically the same, although v2 offers some additional functionality. However, v2 is not back compatible. Make it so and merge them, or alternatively have v1 call on v2 with appropriate parameters so that both functions are kept but use the same underlying background.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/39176803425625/57372425352318)

**Comment by PittSMLlab** [comment]
Function is being deprecated in favor of epoch-based bar plotting.
