### ISSUE TITLE
c3d2mat fails to overwrite files

### ISSUE THREAD

**Issue by pabloi** [PittSMLlab/labTools#47]
When re-loading a subject, c3d2mat checks if the filenames already exist, and asks if it should overwrite in case they do. However, even if you answer 'Yes', the files remain unchanged.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/39176803425625/139862560228145)

**Comment by PittSMLlab** [comment]
Unable to reproduce with current setup.
