### ISSUE TITLE
De-duplicate functions contained in pi-tools submodule

### ISSUE THREAD

**Issue by pabloi** [PittSMLlab/labTools#52]
pi-tools repo (pabloi/pi-tools) was recently added as a submodule of labTools project. This duplicates some functions I (pabloi) had written that were part of both repositories.

In order to avoid duplicates and one function being updated but not the other (and consequently having the code use the wrong function), we should de-duplicate them, leaving a copy ONLY in pi-tools.

Steps:
1. Identify duplicate functions
2. Verify that pi-tools contains the latest/most generic function. If not, update pi-tools copy to state-of-the-art.
3. Delete function from labTools

Notice that this may generate issues with someone who has downloaded a recent copy of labTools but not of the latest submodule version, but I see no better solution (users will just have to update submodules manually in the worst case scenario).

**Comment by PittSMLlab** [comment]
Done.
