### ISSUE TITLE
Included BTK is not suitable for all operating systems

### ISSUE THREAD

**Issue by PittSMLlab** [PittSMLlab/labTools#62]
I am not sure if this is exactly and 'issue' but we should perhaps include other btks or at least a note in the readme files so that people could figure this out themselves.

**Comment by pabloi** [comment]
Agreed. I don't think we should include any BTK at all, since it is a package sourced by others. We should just say that people should download BTK from [here](https://code.google.com/archive/p/b-tk/downloads).
